### ISSUE TITLE
Matějův komentář

### ISSUE THREAD

**Issue by Amatthe** [SimonaPixova/ukolCV#1]
Ahoj,
líbí se mi, jak je to jednoduché a funkční. Nejvíc se mi líbí práce s tím obrázkem u Pracovních zkušeností, i když na velkém monitoru je dost vpravo - ale to se ještě budete učit, jak pracovat s různými velikostmi displejů. 
Jen teda nevím, jak u tebe, ale mně ten font Satisfy nezobrazuje české znaky. Škoda :(

**Comment by SimonaPixova** [comment]
Ahoj, to máš pravdu. Já se tak soustředila na jiné věci, že jsem si toho vůbec nevšimla. Teď nechápu, jak jsem to mohla přehlédnout :) Děkuji za info, alespoň vím, na co si dávat pozor.
